services:
  - type: web
    name: investment-tracker
    env: node
    plan: free
    buildCommand: npm install && npm rebuild
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production